// Alle UI-Texte zentral (Spec §4) — Englisch, sentence case. i18n-Ausbau später.
export const STRINGS = {
  viewTitle: "Local image generator",
  openCommand: "Open generator",
  promptPlaceholder: "Describe the image…",
  generate: "Generate",
  reroll: "Reroll",
  create: "Create",
  insert: "Insert",
  steps: "Steps",
  seed: "Seed",
  randomSeed: "Randomize seed",
  statusChecking: "Checking GPU…",
  statusReady: "Ready",
  statusNoWebgpu: "WebGPU is not available. This plugin needs macOS or Windows with a supported GPU (Linux support depends on drivers).",
  statusNoF16: "This GPU lacks fp16 support (shader-f16), which the model requires.",
  statusDownloading: (pct: number) => `Downloading model… ${pct}%`,
  statusGenerating: (step: number, total: number) => `Generating… step ${step}/${total}`,
  statusError: (msg: string) => `Error: ${msg}`,
  emptyNoModel: "The model (~2.5 GB) is not downloaded yet.",
  emptyNoModelCta: "Download model (~2.5 GB)",
  emptyNoImage: "Enter a prompt and press Generate.",
  insertNeedsEditor: "Open a note to insert the image",
  saveFailed: (msg: string) => `Save failed: ${msg}`,
  oomHint: "Generation failed. Try closing other apps — the model needs roughly 4–7 GB of free memory.",
  settingsModelHeading: "Model",
  settingsModelDesc: "SD-Turbo (ONNX, fp16) is downloaded from Hugging Face after you explicitly start it. Stored in the local browser cache, outside your vault.",
  settingsDownload: "Download",
  settingsDelete: "Delete model",
  settingsDeleteConfirm: "Delete the downloaded model files (~2.5 GB)? You can download them again anytime.",
  settingsOutputHeading: "Output",
  settingsOutputFolder: "Image folder",
  settingsOutputFolderDesc: "Where generated images are saved. Leave empty to use Obsidian's attachment folder.",
  presetsLabel: "Styles",
  history: "Recent prompts",
  historyEmpty: "No prompts yet",
  settingsNoteFolder: "Note folder",
  settingsNoteFolderDesc: "Where result notes are saved. Leave empty to put them next to the image.",
  settingsCreateMode: "Create button",
  settingsCreateModeDesc: "Whether Create saves just the image, or also a note with the settings in its frontmatter and the image embedded.",
  settingsCreateModeImage: "Image only",
  settingsCreateModeNote: "Image + note",
  settingsDefaultSteps: "Default steps",
  settingsDefaultStepsDesc: "Starting value of the steps slider. SD-Turbo is trained for 1–4 steps.",
  settingsPresetsHeading: "Styles",
  settingsPresetsDesc: "Style chips shown under the prompt. Clicking a chip appends its text to the prompt.",
  settingsPresetLabel: "Label",
  settingsPresetSuffix: "Prompt text",
  settingsPresetAdd: "Add style",
  settingsPresetDelete: "Delete style",
  settingsDangerHeading: "Danger zone",
  saved: (path: string) => `Saved: ${path}`,
  noteFailed: (msg: string, imagePath: string) => `Image saved to ${imagePath}, but the note failed: ${msg}`,
  cancel: "Cancel",
  confirm: "Delete",
} as const;
