// Alle UI-Texte zentral (Spec §4) — Englisch, sentence case. i18n-Ausbau später.
export const STRINGS = {
  viewTitle: "Local image generator",
  openCommand: "Open generator",
  promptPlaceholder: "Describe the image…",
  generate: "Generate",
  regenerate: "Regenerate",
  create: "Create",
  insert: "Insert",
  steps: "Steps",
  seed: "Seed",
  randomSeed: "Randomize seed",
  statusChecking: "Checking GPU…",
  statusReady: "Ready",
  statusNoWebgpu: "WebGPU is not available. This plugin needs macOS or Windows with a supported GPU (Linux support depends on drivers).",
  statusNoF16: "This GPU lacks fp16 support (shader-f16), which the model requires.",
  statusDownloading: (pct: number) => `Downloading model… ${pct}%`,
  statusGenerating: (step: number, total: number) => `Generating… step ${step}/${total}`,
  statusError: (msg: string) => `Error: ${msg}`,
  emptyNoModel: "The model (~2.5 GB) is not downloaded yet.",
  emptyNoModelCta: "Download model (~2.5 GB)",
  emptyNoImage: "Enter a prompt and press Generate.",
  insertNeedsEditor: "Open a note to insert the image",
  oomHint: "Generation failed. Try closing other apps — the model needs roughly 4–7 GB of free memory.",
  settingsModelHeading: "Model",
  settingsModelDesc: "SD-Turbo (ONNX, fp16) is downloaded from Hugging Face after you explicitly start it. Stored in the local browser cache, outside your vault.",
  settingsDownload: "Download",
  settingsDelete: "Delete model",
  settingsDeleteConfirm: "Delete the downloaded model files (~2.5 GB)? You can download them again anytime.",
  settingsOutputHeading: "Output",
  settingsOutputFolder: "Image folder",
  settingsOutputFolderDesc: "Where generated images are saved. Leave empty to use Obsidian's attachment folder.",
  cancel: "Cancel",
  confirm: "Delete",
} as const;
